package inf112.skeleton.app.map;


/**
 *  Returns name of given tile id.
 */
public enum Tiles {



    PUSHER1(1),
    PUSHER2(2),
    PUSHER3(3),
    PUSHER4(4),
    FLOOR(5),
    PIT(6),
    REPAIR_SITE_DOUBLE(7),
    WALL_BOTTOM_RIGHT_CORNER(8),
    PUSHER5(9),
    PUSHER6(10),
    PUSHER7(11),
    PUSHER8(12),
    DOUBLE_CONVEYOR_UP(13),
    DOUBLE_CONVEYOR_RIGHT(14),
    REPAIR_SITE_SINGLE(15),
    WALL_TOP_RIGHT_CORNER(16),

    //Double conveyor
    DOUBLE_CONVEYOR_LEFT_DOWN(17),
    DOUBLE_CONVEYOR_UP_LEFT(18),
    DOUBLE_CONVEYOR_UP_RIGHT(19),
    DOUBLE_CONVEYOR_RIGHT_DOWN(20),
    DOUBLE_CONVEYOR_DOWN(21),
    DOUBLE_CONEYOR_LEFT(22),
    WALL_RIGHT(23),
    WALL_LEFT_TOP_CORNER(24),
    DOUBLE_CONVEYOR_DOWN_RIGHT(25),
    DOUBLE_CONVEYOR_RIGHT_UP(26),
    DOUBLE_CONVEYOR_LEFT_UP(27),
    DOUBLE_CONVEYOR_DOWN_LEFT(28),
    WALL_DOWN(29),
    WALL_LEFT(30),
    WALL_TOP(31),
    WALL_LEFT_DOWN_CORNER(32),

    //Normal conveyor
    NORMAL_CONVERYOR_LEFT_DOWN(33),
    NORMAL_CONVERYOR_UP_LEFT(34),
    NORMAL_CONVERYOR_UP_RIGHT(35),
    NORMAL_CONVERYOR_RIGHT_DOWN(36),

    //Laser (Position) (Shooting Direction)
    LASER_DOWN_UP(37),
    LASER_LEFT_RIGHT(38),
    LASERBEAM_HORIZONTOL(39),
    LASERBEAM_CROSS(40),


    NORMAL_CONVERYOR_DOWN_RIGHT(41),
    NORMAL_CONVERYOR_RIGHT_UP(42),
    NORMAL_CONVERYOR_LEFT_UP(43),
    NORMAL_CONVERYOR_DOWN_LEFT(44),
    LASER_TOP_DOWN(45),
    LASER_RIGHT_LEFT(46),
    LASERBEAM_VERTICAL(47),
    EMPTY(48),
    NORMAL_CONVERYOR_UP(49),
    NORMAL_CONVERYOR_DOWN(50),
    NORMAL_CONVERYOR_LEFT(51),
    NORMAL_CONVERYOR_RIGHT(52),
    GEAR_ROTATE_LEFT(53),
    GEAR_ROTATE_RIGHT(54),
    FLAGG1(55),
    //56 is blank
    NORMAL_CONVEYOR_TO_UP__FROM_LEFT_AND_DOWN(57),
    NORMAL_CONVEYOR_TO_RIGHT_FROM_UP_AND_LEFT(58),
    NORMAL_CONVEYOR_TO_DOWN_FROM_RIGHT_AND_UP(59),
    NORMAL_CONVEYOR_TO_LEFT_FROM_DOWN_AND_RIGHT(60),
    
    NORMAL_CONVEYOR_TO_RIGHT_FROM_UP_AND_DOWN(61),
    NORMAL_CONVEYOR_TO_DOWN_FROM_RIGHT_AND_LEFT(62),
    FLAGG2(63),
    //64 is blank
    NORMAL_CONVEYOR_TO_UP_FROM_RIGHT_AND_DOWN(65),
    NORMAL_CONVEYOR_TO_RIGHT_FROM_LEFT_AND_DOWN(66),
    NORMAL_CONVEYOR_TO_DOWN_FROM_LEFT_AND_UP(67),
    NORMAL_CONVEYOR_TO_LEFT_FROM_RIGHT_AND_UP(68),
    NORMAL_CONVEYOR_TO_UP_RFOM_RIGHT_AND_LEFT(69),
    NORMAL_CONVEYOR_TO_LEFT_FROM_UP_AND_DOWN(70),
    FLAGG3(71),
    //72 is blank
    DOUBLE_COONVEYOR_TO_UP_FROM_LEFT_AND_DOWN(73),
    DOUBLE_COONVEYOR_TO_RIGHT_FROM_LEFT_AND_UP(74),
    DOUBLE_COONVEYOR_TO_DOWN_FROM_RIGHT_AND_UP(75),
    DOUBLE_COONVEYOR_TO_LEFT_FROM_RIGHT_AND_DOWN(76),
    DOUBLE_COONVEYOR_TO_UP_FROM_RIGHT_AND_DOWN(77),
    DOUBLE_COONVEYOR_TO_RIGHT_FROM_LEFT_AND_DOWN(78),
    FLAGG4(79),
    //80 is blank
    DOUBLE_COONVEYOR_TO_RIGHT_FROM_UP_AND_DOWN(81),
    DOUBLE_COONVEYOR_TO_DOWN_FROM_RIGHT_AND_LEFT(82),
    DOUBLE_COONVEYOR_TO_LEFT_FROM_UP_AND_DOWN(83),
    DOUBLE_COONVEYOR_TO_UP_FROM_LEFT_AND_RIGHT(84),
    DOUBLE_COONVEYOR_TO_LEFT_FROM_RIGHT_AND_UP(85),
    DOUBLE_COONVEYOR_TO_DOWN_FROM_LEFT_AND_UP(86),
    CONED_WALL_DOWN(87),
    //88 is blank
    TEMP1(89),
    TEMP2(90),
    TEMP3(91),
    TEMP4(92),  //void?
    CONE_WALL_LEFT(93),
    CONE_WALL_UP(94),
    CONE_WALL_RIGHT(95),
    //96 is blank
    TEMP5(97),
    TEMP6(98),
    TEMP7(99),
    TEMP8(100),
    LASER_BEAM_CRISSCROSS(101),
    LASER_BEAM_PARALLEL_VERTICAL(102),
    LASER_BEAM_PARALLEL_HORIZONTAL(103),
    //104 is blank
    TEMP9(105),
    TEMP10(106),
    TEMP11(107),
    TEMP12(108),
    TEMP13(109),
    TEMP14(110),
    //111 is blank
    TEMP15(112),
    TEMP16(113),
    TEMP17(114),
    TEMP18(115),
    TEMP19(116),
    TEMP20(117),
    //118 is blank
    DOCKING_BAY1(119),
    DOCKING_BAY2(120),
    DOCKING_BAY3(121),
    DOCKING_BAY4(122),
    //125-128 is blank
    DOCKING_BAY5(129),
    DOCKING_BAY6(130),
    DOCKING_BAY7(131),
    DOCKING_BAY8(132);
	//133-136 is irrelevant blank


    private final int tileId;

    //Constructor
    Tiles (int id) {
        this.tileId = id;
    }

    /**
     * @returns tileID of tile
     */
    public int getTileID() {
        return tileId;
    }


    //    CONVEYOR_EXPRESS_JOIN_SOUTH_FROM_NORTH_AND_EAST(75),

}
